import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'
import { Toaster } from 'react-hot-toast'
import StyledComponentsRegistry from '../contexts/AntdRegistry'
import Provider from '../contexts/AuthContext'
import ModalProvider from '../contexts/ModalContext'
import ThemeProvider from '../contexts/ThemeProvider'
import './globals.css'
import Loading from './loading'
import '@/css/draculaTheme.css'
import EditorProvider from '../contexts/EditorContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tech Blog',
  description: 'Generated by create next app',
  icons: '/blog.png'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} scrollbar-hide relative`}>
        <Suspense fallback={<Loading />}>
          <StyledComponentsRegistry>
            <EditorProvider>
              <ThemeProvider>
                <ModalProvider>
                  <Provider>
                    <Toaster
                      toastOptions={{
                        className: 'dark:bg-gray-800 dark:text-white',
                      }}
                    />
                    {children}
                  </Provider>
                </ModalProvider>
              </ThemeProvider>
            </EditorProvider>
          </StyledComponentsRegistry>
        </Suspense>
      </body>
    </html>
  )
}
