import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'
import { Toaster } from 'react-hot-toast'
import StyledComponentsRegistry from './contexts/AntdRegistry'
import Provider from './contexts/AuthContext'
import ThemeProvider from './contexts/ThemeProvider'
import './globals.css'
import Loading from './loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tuấn Đặng Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} scrollbar-hide`}>
        <Suspense fallback={<Loading />}>
          <StyledComponentsRegistry>
            <ThemeProvider>
              <Provider>
                <Toaster
                  toastOptions={{
                    className: 'dark:bg-gray-800 dark:text-white',
                  }}
                />
                {children}
              </Provider>
            </ThemeProvider>
          </StyledComponentsRegistry>
        </Suspense>
      </body>
    </html>
  )
}
